### ISSUE TITLE
throw error when I run the script on windows

### ISSUE THREAD

**Issue by Jarvin-Guan** [MakeBluetooth/rolling-spider#1]
Error: Cannot find module 'bluetooth-hci-socket'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Jarvin\Desktop\rolling-spider-master\node_modules\rolling-spider\node_modules\noble\lib\hci-socket\hci.js:6:26)

**Comment by sandeepmistry** [comment]
@Jarvin-Guan please see the noble Windows prerequisites section: https://github.com/sandeepmistry/noble#windows

After setting those up, you can run "npm install bluetooth-hci-socket" to get the required dependency installed.

@don has made a video on this: https://www.youtube.com/watch?v=mL9B8wuEdms

Closing for now, re-open if you still have issues after trying the above.

**Comment by Jarvin-Guan** [comment]
thankyou
